// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOFkwA92nyZu8pedvSZv_1A1Z1cyMcgU',
    appId: '1:391848317273:web:6b18ce16669f1a7f247c48',
    messagingSenderId: '391848317273',
    projectId: 'flutter-firebase-auth-66211',
    authDomain: 'flutter-firebase-auth-66211.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-66211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq42lqR7tyJKObTSalYT54OV61PkH6y9o',
    appId: '1:391848317273:android:2bd3e8d424b5f5fc247c48',
    messagingSenderId: '391848317273',
    projectId: 'flutter-firebase-auth-66211',
    storageBucket: 'flutter-firebase-auth-66211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgEdlTLcwPSyLiyoQG3WXSrdmqNzwKQE',
    appId: '1:391848317273:ios:926b469aca9f7076247c48',
    messagingSenderId: '391848317273',
    projectId: 'flutter-firebase-auth-66211',
    storageBucket: 'flutter-firebase-auth-66211.appspot.com',
    androidClientId: '391848317273-3eahbk9mja9mdedfkka1klerese06oh6.apps.googleusercontent.com',
    iosClientId: '391848317273-883e35d7tc4ffmo5cdpf1rlo77bg4qe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdgEdlTLcwPSyLiyoQG3WXSrdmqNzwKQE',
    appId: '1:391848317273:ios:926b469aca9f7076247c48',
    messagingSenderId: '391848317273',
    projectId: 'flutter-firebase-auth-66211',
    storageBucket: 'flutter-firebase-auth-66211.appspot.com',
    androidClientId: '391848317273-3eahbk9mja9mdedfkka1klerese06oh6.apps.googleusercontent.com',
    iosClientId: '391848317273-883e35d7tc4ffmo5cdpf1rlo77bg4qe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );
}
